# Override for development - automatically applied with docker-compose up
services:
  app:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    
  db:
    ports:
      - "5432:5432"