# Full Next.js deployment with dependency installation
services:
  app:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "
        echo '🚀 Starting full Next.js deployment...' &&
        apk add --no-cache git &&
        git clone --depth 1 https://github.com/rodsct/saasiav4.git . &&
        echo '🔧 Using bare next.config.mjs...' &&
        cp next.config.bare.mjs next.config.mjs &&
        echo '📦 Installing all dependencies...' &&
        npm install --silent &&
        echo '🗄️ Generating Prisma client...' &&
        npx prisma generate &&
        echo '🏃 Starting Next.js development server...' &&
        npm run dev
      "
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-saas_personal_agent}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3001}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-secret-key}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL:-noreply@localhost}
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-saas_personal_agent}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres_data: