# Override file for Easypanel - DO NOT DELETE
# Easypanel automatically looks for this file
# This file ensures build context is correct

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile