# Development mode - No build required, faster startup
services:
  app:
    image: node:20-alpine
    working_dir: /tmp
    command: >
      sh -c "
        echo '🚀 Starting in development mode...' &&
        apk add --no-cache git &&
        rm -rf /app &&
        git clone --depth 1 https://github.com/rodsct/saasiav4.git /app &&
        cd /app &&
        echo '📦 Installing core dependencies...' &&
        npm install next@15.1.0 react@18.2.0 react-dom@18.2.0 autoprefixer@^10 --silent &&
        echo '🏃 Starting development server...' &&
        npx next dev
      "
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-saas_personal_agent}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3001}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-secret-key}
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-saas_personal_agent}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres_data: